### PR TITLE
PIC32 support

### PR DESCRIPTION
**Pull request by Adilla**

### CODE REVIEW

**Comment by Vertmo** [comment]
I think you should rebase this branch to target `master` instead of `generic`, now that `generic` has been merged

**Comment by stevenvar** [comment]
"This branch cannot be rebased due to conflicts
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch."

Does someone else have admin permissions?

**Comment by Vertmo** [comment]
> "This branch cannot be rebased due to conflicts
> Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch."
> 
> Does someone else have admin permissions?

Have you tried rebasing it inside GitHub ? I think in this case it probably needs to be done in-terminal, although that's a tedious and error-prone process unfortunately...

**Comment by Vertmo** [comment]
I think we can close this as this is replaced by #26

**Pull request closed without merging**
